### PR TITLE
Fix UTF8 encoding being used instead of Shift-JIS

### PR DESCRIPTION
**Pull request by AnimatedSwine37**
According to [TGE's template](https://github.com/tge-was-taken/010-Editor-Templates/blob/c74cbd39b67829c37d3e781a23f874db7a6028e1/releases/cri_archives/cri_archives_rel_1.bt#L18C35-L18C35) Shift-JIS is 0 and UTF-8 is 1, this was swapped around when getting the encoding.

### CODE REVIEW

**Comment by Sewer56** [comment]
I probably did an oopsie here.

That said, did you confirm with a real CPK just in case? I assume this popped up somewhere given it was found.

**Comment by AnimatedSwine37** [comment]
Yeah, it happened with P3P's umd0.cpk. There are a few files with Japanese characters in them which had broken names prior to my change.

**Comment by Sewer56** [comment]
alright, bet.

Also I need some system for getting faster GitHub notifications. Most repos I use Discord webhooks, but sometimes I can miss stuff.

**Comment by Sewer56** [comment]
I'll also get a release of the hook out, since it's affected by this bug technically too.

**Pull request merged**
